import React, { useEffect } from "react";
import Head from "next/head";
import NumberShowBoard from "../components/NumberShowBoard";
import MainContainer from "../components/MainContainer";
import { useAppDispatch, useAppSelector } from "../redux/hooks";
import { liveResultFetch } from "../redux/actions";

import Box from "@mui/material/Box";
import RenderLoader from "../components/RenderLoader";
export default function Index() {
  const dispatch = useAppDispatch();

  const fetchResult = () => {
    dispatch<any>(liveResultFetch());
  };

  const { data, loading } = useAppSelector((state) => state.liveResultReducer);

  useEffect(() => {
    if (!data) {
      return fetchResult();
    }else{
      const setInt = setInterval(() => {
        fetchResult();
      }, 5000);
  
      return () => clearInterval(setInt);
    }

    
  }, []);

  return (
    <>
      <Head>
        <title>Myanmar 2D live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      {data ? (
        <>
          <NumberShowBoard />
          <MainContainer />
        </>
      ) : (
        <RenderLoader />
      )}
    </>
  );
}
